version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ..:/workspaces/mareweb:cached
      - mare-web-build:/workspaces/mareweb/build
    command: sleep infinity
    environment:
      - DISPLAY=novnc:0
    networks:
      - x11-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  novnc:
    image: theasp/novnc:latest
    environment:
      - DISPLAY_WIDTH=2560
      - DISPLAY_HEIGHT=1440
      - RUN_XTERM=no
    ports:
      - "6080:8080"
    hostname: novnc
    networks:
      - x11-network
    # https://github.com/SeleniumHQ/docker-selenium/issues/2045
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  mare-web-build:

networks:
  x11-network:
    driver: bridge