name: Deploy Resources on AWS

on:
  push:
    branches: [main]
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout
  pull-requests: write
  issues: read

concurrency:
  group: production
  cancel-in-progress: false

jobs:
  publish:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::184077986974:role/computable-coffee-cdktf-cloudfront-deploy
          aws-region: us-east-1

      - name: Setup Emscripten toolchain
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: latest
          cache: "emsdk"
          actions-cache-folder: 'emsdk-cache'

      - name: Build for Web
        run: |
          emcmake cmake -B build-web
          cmake --build build-web
          mkdir dist
          cp build-web/basic_texture.js dist/
          cp build-web/basic_texture.data dist/
          cp build-web/basic_texture.wasm dist/
          cp build-web/basic_texture.html dist/index.html
            
      - name: Use Node.js 20.x
        working-directory: ${{ github.workspace }}/iac
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - name: Install dependencies
        working-directory: ${{ github.workspace }}/iac
        run: npm ci

      - name: Run Tests Backend
        working-directory: ${{ github.workspace }}/iac
        run: npm test

      - name: Run Terraform CDK
        uses: hashicorp/terraform-cdk-action@v0.2
        with:
          terraformVersion: 1.6.4
          cdktfVersion: 0.19.1
          stackName: computable-coffee
          mode: auto-approve-apply
          workingDirectory: ${{ github.workspace }}/iac
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          commentOnPr: false

      - name: Get CloudFront Distribution ID
        working-directory: ${{ github.workspace }}/backend/cdktf.out/stacks/computable-coffee
        run: |
          echo "DISTRIBUTION=$(terraform output -raw distribution_id)" >> $GITHUB_ENV

      - name: Invalidate CloudFront
        uses: chetan/invalidate-cloudfront-action@v2
        env:
          DISTRIBUTION: ${{ env.DISTRIBUTION }}
          PATHS: "/*"
          AWS_REGION: "us-east-1"
